services:
  backend:
    build: ./backend
    container_name: portfolio-backend
    environment:
      FRONTEND_URL: ${FRONTEND_URL}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER_READONLY}
      DB_PASSWORD: ${DB_PASSWORD_READONLY}
    volumes:
      - ./backend:/app
    ports:
      - "8002:8002"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8002
      
  frontend:
    build: ./frontend
    container_name: portfolio-frontend
    environment:
      VITE_BACKEND_URL: ${BACKEND_URL}
      VITE_RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
      VITE_PROJECT_STATUS: ${PROJECT_STATUS}
      VITE_FRONTEND_URL: ${FRONTEND_URL}
      VITE_FRONTEND_PORT: ${FRONTEND_PORT}
      VITE_DEFAULT_LOCALE: ${DEFAULT_LOCALE}
      VITE_FALLBACK_LOCALE: ${FALLBACK_LOCALE}
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    ports:
      - "5173:5173"
      - "7002:7002"

  redis:
    image: redis
    container_name: portfolio-redis

  apigateway:
    image: nginx
    container_name: portfolio-apigateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    ports:
      - "8080:80"

  db:
    image: postgres
    container_name: portfolio-db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      # POSTGRES_PASSWORD: ${DB_PASSWORD_READONLY}
      # POSTGRES_USER: ${DB_USER_READONLY}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
    volumes:
      - ./backend/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    
  db-adminer:
    image: adminer
    container_name: portfolio-db-adminer
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
  